job('Docker job') {
    description("Docker job generated by the DSL on ${new Date()}")
    scm {
        git('https://github.com/wardviaene/docker-demo.git') {  node ->
            node / gitConfigName('DSL Docker Demo')
            node / gitConfigEmail('dsl-docker-demo@madeupemailaddress.com')
        }
    }
    triggers {
        scm('H/5 * * * *')
    }
    wrappers {
        nodejs('nodejs')
    }
    steps {
        dockerBuildAndPublish {
            repositoryName('ignia/demo_jenkins')
            tag('${GIT_REVISION,length=9}')
            registryCredentials('dockerhub')
            forcePull(false)
            forceTag(false)
            createFingerprints(false)
            skipDecorate()
        }
    }
}
